version: '3.5'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./app:/base/app
      - ./public:/base/public
    ports:
      - 3000:3000
    links:
      - db:nd-db
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
    volumes:
      - ./.data:/var/lib/postgresql/data
      - ./sql:/sql
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./src:/base/src
      - ./public:/base/public
